version: '3.8'

services:
  db:
    image: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - db
    build: ./
    restart: unless-stopped
    env_file: .env
    ports:
      - "${NODE_LOCAL_PORT}:8080"
    stdin_open: true
    tty: true

volumes:
  db:
